"""
Pydantic schemas for data validation and API models.
Ensures type safety and clear data structures across the system.

Enhanced to support multi-leg strategies (spreads, condors, butterflies)
with per-leg strike selection, profit targets, and stop losses.
"""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from enum import Enum


class OptionType(str, Enum):
    CALL = "CALL"
    PUT = "PUT"


class Action(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderLeg(BaseModel):
    """A single leg in a multi-leg options strategy."""
    action: Action
    option_type: OptionType
    strike: float = Field(gt=0)
    expiry: str
    quantity: int = Field(gt=0)
    limit_price: Optional[float] = None


class TradeSignal(BaseModel):
    """
    A trade signal generated by a strategy.
    For multi-leg strategies (spreads, condors, butterflies, calendars),
    use the `legs` field. For single-leg strategies, use the top-level fields.
    """
    strategy_name: str
    symbol: str
    action: str  # BUY, SELL, or COMPLEX for multi-leg
    quantity: int
    strike: float
    expiry: str
    option_type: str  # CALL or PUT
    limit_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    confidence_score: float = 0.0
    risk_warning: str = ""

    # Multi-leg support
    legs: Optional[List[OrderLeg]] = None
    net_debit: Optional[float] = None
    net_credit: Optional[float] = None
    max_loss: Optional[float] = None
    max_profit: Optional[float] = None
    spread_width: Optional[float] = None

    # Strategy metadata
    entry_rules: Optional[Dict[str, Any]] = None
    exit_rules: Optional[Dict[str, Any]] = None
    dte_target: Optional[int] = None
    iv_rank_at_entry: Optional[float] = None


class PortfolioGreeks(BaseModel):
    delta: float = 0.0
    gamma: float = 0.0
    theta: float = 0.0
    vega: float = 0.0
    rho: float = 0.0


class Position(BaseModel):
    symbol: str
    quantity: int
    avg_cost: float
    current_price: float
    pnl: float
    greeks: PortfolioGreeks


class AccountSummary(BaseModel):
    net_liquidation: float
    buying_power: float
    cash: float
    positions: List[Position]
    portfolio_greeks: PortfolioGreeks


class StrategyConfig(BaseModel):
    """Configuration for a strategy's parameters."""
    name: str
    enabled: bool = True
    allocation_pct: float = 10.0
    max_concurrent_positions: int = 5
    profit_target_pct: float = 50.0  # Close at X% of max profit
    stop_loss_multiplier: float = 2.0  # Stop at X times credit received
    min_iv_rank: float = 0.0
    max_iv_rank: float = 100.0
    preferred_dte_min: int = 30
    preferred_dte_max: int = 45
    risk_per_trade_pct: float = 2.0


class MarketDataSnapshot(BaseModel):
    """Normalized market data passed to strategy scan methods."""
    symbol: str
    price: float
    iv: float = 0.0
    iv_rank: float = 0.0
    iv_percentile: float = 0.0
    iv_rank_52w_high: float = 0.0
    iv_rank_52w_low: float = 0.0
    volume: int = 0
    avg_volume: int = 0
    vix: float = 0.0
    vix_term_structure: str = "contango"  # contango or backwardation
    days_to_earnings: Optional[int] = None
    option_chain: Optional[List[Dict[str, Any]]] = None
    owns_shares: bool = False
    shares_owned: int = 0
    daily_range_pct: float = 0.0
    timestamp: Optional[str] = None
